### ISSUE TITLE
Different display of the WebView description in Authorizations screen

### ISSUE THREAD

**Issue by mnewlive** [saltedge/sca-authenticator-android#125]
**Summary:**  
Different display of the `WebView` description in Authorizations screen

**Actual behavior:**  
Tested using the `dev` build:
* On Xiaomi phones, the description in  Authorizations screen is not displayed correctly.
* Tested on Pixel 2, everything is displayed correctly.

**Comment by AlexLobaciov** [comment]
@mnewlive @ConstantinKV   
Current LIVE version screenshots:
<details>
  <summary><b>Screenshots</b></summary>
![image](https://user-images.githubusercontent.com/38658558/76327449-b0709f80-62f2-11ea-9295-f9f1f9669dc3.png)
![image](https://user-images.githubusercontent.com/38658558/76327462-b5355380-62f2-11ea-9dd6-ed83a11af47d.png)

</details>

Current Alpha version screenshots:

<details>
  <summary><b>Screenshots</b></summary>
![image](https://user-images.githubusercontent.com/38658558/76327422-a8186480-62f2-11ea-8cbf-6472204a3314.png)

![image](https://user-images.githubusercontent.com/38658558/76327408-a2bb1a00-62f2-11ea-8db8-b7abd7a22118.png)

</details>

Please fix the issue. I see here TextView, like WebView is not launching...
