### ISSUE TITLE
Need to validate ProviderData

### ISSUE THREAD

**Issue by mnewlive** [saltedge/sca-authenticator-android#47]

**Comment by mnewlive** [comment]
@AlexLobaciov when user can't connect the provider, we decided to show him a dialog with following message:
> Something went wrong. Unable connect to Provider

Maybe there will be some remarks?

**Comment by AlexLobaciov** [comment]
> @AlexLobaciov when user can't connect the provider, we decided to show him a dialog with following message:
> 
> > Something went wrong. Unable connect to Provider
> 
> Maybe there will be some remarks?

Okay, sure, this case will be rare, as configuration file is preliminary verified by the Salt Edge and Service Provider. For the message, please use this one: "Something went wrong. Unable connect to service provider.". Thanks!
