### ISSUE TITLE
Apply blur instead of alpha on Authorizations final screen

### ISSUE THREAD

**Issue by mnewlive** [saltedge/sca-authenticator-android#49]
Apply blure instead of alpha on final screen

**Comment by AlexLobaciov** [comment]
@mnewlive why when there is "blur" the authorization request data is not present behind the blur?

**Comment by mnewlive** [comment]
@AlexLobaciov currently blur overwrites content from `WebView`(first screenshot)
If we use `TextView` as a container, the content is visible(second screenshot).

![image](https://user-images.githubusercontent.com/6228394/71174162-32f63f80-226d-11ea-9daa-8ebd6a662183.png)
![image](https://user-images.githubusercontent.com/6228394/71174181-3e496b00-226d-11ea-89ee-91e2c88e4f14.png)

**Comment by AlexLobaciov** [comment]
@mnewlive content is important, but keep it as it is for now please, later will be searching for a better solution. TextView is never an option.

**Comment by AlexLobaciov** [comment]
@mnewlive the Blur works correctly on "full-authorization-page" (via push notification), and is not applied on top of information on standard "Authorizations" page. Please adjust for Blur to work correctly on "Authorizations" page.
