### ISSUE TITLE
Make "No internet" message global

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#68]
**Summary:**  
If customer is using our application without the Internet Connection, we should inform the customer no matter what action customer wants to do - most important action will not work without the internet

**Steps to reproduce:**  
Disable internet (4G/Wi-Fi), open the app

**Actual behavior:**  
"No internet connection" message is only seen once there should be fetched an authorization request. 

**Expected behavior:**  
"No internet connection" message should be seen globally. Should we change the naming to "You're offline", as more user-friendly?

**Comment by mnewlive** [comment]
Some useful links for this issue:
https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION
https://developer.android.com/guide/components/broadcasts.html#context-registered-receivers

**Comment by AlexLobaciov** [comment]
Looks fine
![Screenshot_2019-11-21-20-23-50-233_com saltedge authenticator](https://user-images.githubusercontent.com/38658558/69365389-e97df900-0c9c-11ea-93b8-5a21bbe8a6dc.jpg)
