### ISSUE TITLE
No extra confirm. and app block if unattended

### ISSUE THREAD

**Issue by AlexLobaciov** [saltedge/sca-authenticator-android#80]
**Summary:**  
We should decrease the indirect fraud opportunities and allow customer to allow/deny any actions while he is active.

**Actual behavior:**  
- 1) App does not block if user does not interact with the app for certain period of time.
- 2) Currently we require for customer to confirm the action once again with biometric/PIN input, if accessed not via the push-notification

**Expected behavior:**  
- [x] If user does not interact with the app for 1 minute, app is automatically blocked (unlock screen is displayed as a result). User should be in "active" state right after what user unlocked the app via biomteric/PIN input. User is active as long as there is any interaction with Salt Edge Authenticator app.
- [x] After what screen is blocked due to user inactivity, add a toast message "Application was locked due to inactivity".
- [x] Disable all logic that requires the extra action confirmation via the biometric/PIN input. So, no matter how customer accesses the application (directly or via push notification), all actions can be confirmed as long as user is active. 

___

Thanks!

**Comment by AlexLobaciov** [comment]
- 1) Once app is just opened > app is not blocked in 1 minute of inactivity.
- 2) On "Scan QR" action > app is not blocked in 1 minute of inactivity
- 3) When app locks after 1 minute, it requires PIN. Please make it require Fingerprint as priority.

Please adjust.

**Comment by mnewlive** [comment]
@AlexLobaciov Update please status of the task

**Comment by AlexLobaciov** [comment]
@mnewlive thanks for reminder.

Within testing, found annoying issue:  
- After 1 minute the behavior is quite correct, but Fingerprint is quite often triggered before 1 minute passes. It happens almost every time, on 10th-55th second. Main happens on screens: QR code scanner, Authorizations page, Provider connect WebView. Videos provided in PM.

**Comment by AlexLobaciov** [comment]
@mnewlive 

1) the problem with double lock is still persisting. App is not locked but is asking for Fingerprint and message that app was locked is shown. In 1 minute, when it's the right time for app lock, app locks and shows message - as a result - for 2ns time.
2) If user has moved the app on background - timer should not be applied here. Once app is on the background - app should always be locked. Please make sure app is always locked when not used.
3) The Toast message is not seen once app blocks, as it is under the grey screen of the Fingerprint. Hence, please either make for Toast message the highest priority, so that the message is clearly seen when app is locked, or you can also use Snack bar for message for example, and say, make a warning 5-seconds before the app is locked that "Soon app will be locked due to inactivity". Please choose the most suitable method.

**Comment by AlexLobaciov** [comment]
@mnewlive 

1) Please change the snack bar message to "Application will be locked due to inactivity", and please make it appear for 5 seconds before app is locked. 
2) For "Scan QR" the app locks in 1 minute, please change to 2 minutes.

All else is good! Thanks!

**Comment by AlexLobaciov** [comment]
@mnewlive when the snack bar notification appears, to cancel the lock I can use only "Cancel" button. Please make it disappear by any tap on screen, not only by tap on "Cancel" button.

**Comment by ConstantinKV** [comment]
@AlexLobaciov normal behave for snackbar it is dismiss by swipe
